#!/usr/bin/env bash
HOST="116.193.191.104"
HOST_AN="10.0.2.2"
HOST_SER="127.0.0.1"
PORT="3100"

# get time
TIME=$(date +%Y%m%d%H%M%S)
LOGIN="sshpass -p StartOurDream2022 ssh posapp@$HOST"
ENV_DEV="DATABASE_URL=\"mysql://root:Makuro_123@localhost:3306/dbreportmobile\""
ENV_PRO="DATABASE_URL=\"mysql://probus:7971515@localhost:3306/dbtgho\""

CONFIG_DEV="
class Config{
    static const isDevAndroid = false;
    static const isDevWeb = true;
    static const weblUrl = 'http://$HOST_SER:$PORT/apiv2';
    static const androidUrl = 'http://$HOST_AN:$PORT/apiv2';
    static const serverUrl = 'https://$HOST:$PORT/apiv2';
    static const getUrl = isDevAndroid? androidUrl : isDevWeb? weblUrl : serverUrl;
}
"

CONFIG_PRO="
class Config{
  static const isDevAndroid = false;
  static const isDevWeb = false;
  static const weblUrl = 'http://$HOST_SER:$PORT/apiv2';
  static const androidUrl = 'http://$HOST_AN:$PORT/apiv2';
  static const serverUrl = 'https://$HOST:$PORT/apiv2';
  static const getUrl = isDevAndroid? androidUrl : isDevWeb? weblUrl :  serverUrl;
}
"
help() {
    echo "$(tput setaf 2)
Name:
    presto
Usage:
    presto [options] | ./presto [options]
Options: 
    runs, -rs: run presto server
    runc, -rc: run presto client
    help, -h: show this help
    runc, -rc: run presto on chrome
    buildw, -bw: build web release
    gen, -g: generate presto
    login, -l: login to server
    push, -p: push to server
    seed , -s: seed database
   

$(tput sgr0)"
}

case $1 in
runs | -rs)
    cd server && nodemon .
    ;;
runc | -rc)
    flutter run -d chrome
    ;;
buildw | -bw)
    flutter build web --release
    ;;
gen | -g)
    cd server && prisma generate
    ;;
login | -l)
    $LOGIN
    ;;
push | -p)
    echo -e $ENV_PRO >server/.env
    echo -e $CONFIG_PRO >lib/config.dart
    flutter build web --release --web-renderer html
    git add .
    git commit -m "$TIME"
    git push origin main
    echo -e $ENV_DEV >server/.env
    echo -e $CONFIG_DEV >lib/config.dart
    $LOGIN -t "source ~/.nvm/nvm.sh && pm2 stop all && cd mobile_report_apk && git pull origin main && cd server &&  npm install && prisma generate && pm2 restart all"
    ;;
seed | -s)
    cd server/seeds && node create_table.js && cd .. && prisma generate && cd seeds && node seed.js
    ;;
seeds | -se)
    $LOGIN -t "source ~/.nvm/nvm.sh && pm2 stop all && cd mobile_report_apk && ./presto -s && pm2 restart all"
    ;;
ctbl | -ct)
    CRT="
    DROP TABLE IF EXISTS Auth;
    CREATE TABLE Auth(
        id Int NOT NULL AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    SELECT * FROM Auth;"
    case $2 in
    -c) mysql -uroot -pMakuro_123 -hlocalhost -P3306 -Ddbreportmobile -e "$CRT" ;;
    -s) $LOGIN -t "mysql -uprobus -p7971515 -hlocalhost -P3306 -Ddbtgho -e \"$CRT\"" ;;
    *) echo "Please input -c or -s" ;;
    esac

    ;;

help | -h)
    help
    ;;
*) echo "-h help" ;;
esac
