#!/usr/bin/env bash

# get time
TIME=$(date +%Y%m%d%H%M%S)
LOGIN="sshpass -p StartOurDream2022 ssh posapp@116.193.191.104"
ENV_DEV="DATABASE_URL=\"mysql://root:Makuro_123@localhost:3306/dbreportmobile\""
ENV_PRO="DATABASE_URL=\"mysql://probus:7971515@localhost:3306/dbtgho\""
help() {
    echo "$(tput setaf 2)
Name:
    presto
Usage:
    presto [options] | ./presto [options]
Options: 
    runs, -rs: run presto server
    help, -h: show this help
    runc, -rc: run presto on chrome
    buildw, -bw: build web release
    gen, -g: generate presto
    login, -l: login to server
    push, -p: push to server
    seed , -s: seed database
   

$(tput sgr0)"
}

if [[ $# -eq 1 ]]; then
    case $1 in
    runs | -rs)
        cd server && nodemon .
        ;;
    runc | -rc)
        flutter run -d chrome
        ;;
    buildw | -bw)
        flutter build web --release
        ;;
    gen | -g)
        cd server && prisma generate
        ;;
    login | -l)
        $LOGIN
        ;;
    push | -p)
        echo $ENV_PRO >server/.env
        flutter build web --release
        git add .
        git commit -m "update"
        git push origin main
        echo $ENV_DEV >server/.env
        $LOGIN -t "cd mobile_report_apk && git pull origin main && cd server && source ~/.nvm/nvm.sh && npm install && prisma generate "
        ;;
    seed | -s)
        cd server/seeds && node create_table.js && cd .. && prisma generate && cd seeds && node seed.js
        ;;
    seeds | -se)
        $LOGIN -t "source ~/.nvm/nvm.sh && cd seeds && node create_table.js && cd .. && prisma generate && cd seeds && node seed.js && npm install && prisma generate"
        ;;
    *) echo "-h help" ;;
    esac
else
    help
fi
